language: c
# To build on OSX, switch the previous line to
# language: objective-c
script: 
    - ./travis-tool.sh run_tests
    - cd ..; cd latex; make clean; make
before_install:
    - cd issb
    - curl -OL http://raw.github.com/craigcitro/r-travis/master/scripts/travis-tool.sh
    - chmod 755 ./travis-tool.sh
    - ./travis-tool.sh bootstrap
install:
    - ./travis-tool.sh install_deps

notifications:
    email:
    on_success: change
    on_failure: change
